# v1_deployment_config.yml
---

tasks:
- create:
    name: frontend
    namespace: k8s-project
    spec_template_metadata_labels:
      name: frontend
    spec_template_spec_containers:
    - name: helloworld
      image: openshift/origin-ruby-sample
      ports:
      - container_port: 8080
        protocol: TCP
        name: http-port
    spec_replicas: 5
    spec_selector:
      name: frontend
    spec_triggers:
    - type: ConfigChange
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - helloworld
        _from:
          kind: ImageStreamTag
          name: "origin-ruby-sample:latest"
    strategy_type: Rolling
  name: Create deployment config

- patch:
    name: frontend
    namespace: k8s-project
    spec_template_metadata_labels:
      name: frontend
    spec_template_containers:
    - name: helloworld
      image: "openshift/origin-ruby-sample:v1.0"
      ports:
      - container_port: 9000
        protocol: UDP
        name: udp-port
    spec_replicas: 3
  name: Patch deployment config

- replace:
    name: frontend
    namespace: k8s-project
    spec_template_metadata_labels:
      name: frontend_app
    spec_template_containers:
    - name: helloworld
      image: openshift/origin-ruby-sample:v2
      ports:
      - container_port: 8888
        protocol: TCP
        name: http-port
    spec_replicas: 2
    spec_selector:
      name: frontend_app
    spec_triggers:
    - type: ConfigChange
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - helloworld
        _from:
          kind: ImageStreamTag
          name: "origin-ruby-sample:v2"
    spec_strategy_type: Rolling
  name: Replace deployment config

- remove:
    name: frontend
    namespace: k8s-project
  name: Remove deployment config
